---
title: "ADS506 - Team Project - EDA"
author: "Stephen Kuc, Lane Whitmore, Luis Perez"
date: "2022-11-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r}
library(fpp2)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(zoo)

set.seed(25)
```


```{r}

land.temps <- read.csv("~/USD/ADS506/GlobalLandTemperaturesByCountry.csv")
head(land.temps)

```
```{r}
# let's see what countries we have?
# not going to print all out

head(unique(land.temps$Country), 10)

```
```{r}
# check structure of dataframe

str(land.temps)

```

```{r}
# converting date into date format

land.temps$dt <- as.Date(land.temps$dt)
land.temps
```
```{r}
# creating a new dataframe for each continent

NA.temps <- land.temps[land.temps$Country == 'North America',]
SA.temps <- land.temps[land.temps$Country == 'South America',]
AF.temps <- land.temps[land.temps$Country == 'Africa',]
EU.temps <- land.temps[land.temps$Country == 'Europe',]
AS.temps <- land.temps[land.temps$Country == 'Asia',]
AU.temps <- land.temps[land.temps$Country == 'Australia',]
```

```{r}
# setting all to a TimeSeries object 

NA.ts <- ts(NA.temps$AverageTemperature, start = c(1900), end = c(2010), frequency = 12) 
SA.ts <- ts(SA.temps$AverageTemperature, start = c(1900), end = c(2010), frequency = 12) 
AF.ts <- ts(AF.temps$AverageTemperature, start = c(1900), end = c(2010), frequency = 12) 
EU.ts <- ts(EU.temps$AverageTemperature, start = c(1900), end = c(2010), frequency = 12) 
AS.ts <- ts(AS.temps$AverageTemperature, start = c(1900), end = c(2010), frequency = 12) 
AU.ts <- ts(AU.temps$AverageTemperature, start = c(1900), end = c(2010), frequency = 12) 

```


```{r}
# plotting for each below

naTS <- ts(northAmerica$AverageTemperature, start = c(1900, 1), end = c(2010), frequency = 12) 

plot(naTS)

```

```{r}
plot.ts(NA.ts, xlab = 'Time', ylab = 'Average Temperature', bty = 'l', ylim = c(-20, 40)) 
```
```{r}
summary(NA.ts)
```

```{r}
plot.ts(SA.ts, xlab = 'Time', ylab = 'Average Temperature', bty = 'l', ylim = c(-20, 40))
```


```{r}
#uniq.lm <- tslm(uniq.ts ~ trend + I(trend^2))
plot.ts(AF.ts, xlab = 'Year', ylab = 'Average Temperature', bty = 'l', ylim = c(-20, 40))
#lines(uniq.lm$fitted, lwd = 2)
```

```{r}
plot.ts(EU.ts, xlab = 'Time', ylab = 'Average Temperature', bty = 'l', ylim = c(-20, 40))
```

```{r}
summary(EU.ts)
```

```{r}
plot.ts(AS.ts, xlab = 'Time', ylab = 'Average Temperature', bty = 'l', ylim = c(-20, 40))
```

```{r}
plot.ts(AU.ts, xlab = 'Time', ylab = 'Average Temperature', bty = 'l', ylim = c(-20, 40))
```
